-- local capabilities = vim.tbl_deep_extend(
-- 	"force",
-- 	vim.lsp.protocol.make_client_capabilities(),
-- 	require("cmp_nvim_lsp").default_capabilities()
-- )
-- local lspconfig = require("lspconfig")

-- require("mason").setup()
-- require("mason-lspconfig").setup({
-- 	ensure_installed = {
-- 		"tsserver",
-- 	},
-- 	handlers = {
-- 		function(server_name)
-- 			require("lspconfig")[server_name].setup({})
-- 			capabilities = capabilities
-- 		end,
-- 	},
-- })
